In [3]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [63]:
import sys
import os
import kit as erk 
import pandas as pd
# Change working directory to root so relative paths (like 'data/...') work
if os.path.basename(os.getcwd()) == 'Exercise':
    os.chdir('..')

# Add the current directory (root) to path
if os.getcwd() not in sys.path:
    sys.path.append(os.getcwd())

In [22]:
# Test the import and data loading
hfi = erk.get_hfi_returns()
er = hfi["2000":]
er.head()

/Users/phamthanh/Documents/ESSCA | MSc Finance & Data Analyst/9. Introduction to Portfolio Construction/kit.py:29: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  hfi = pd.read_csv("data/edhec-hedgefundindices.csv",

,Convertible Arbitrage,CTA Global,Distressed Securities,Emerging Markets,Equity Market Neutral,Event Driven,Fixed Income Arbitrage,Global Macro,Long/Short Equity,Merger Arbitrage,Relative Value,Short Selling,Funds Of Funds
date,,,,,,,,,,,,,
2000-01,0.0227,0.0128,0.0088,0.0077,0.0075,0.0088,0.0041,0.0021,0.0075,0.0143,0.0173,0.0427,0.0169
2000-02,0.0267,-0.0022,0.0421,0.0528,0.0253,0.0346,0.0097,0.0408,0.0699,0.0239,0.0185,-0.1340,0.0666
2000-03,0.0243,-0.0138,0.0103,0.0318,0.0134,0.0069,-0.0061,-0.0104,0.0006,0.0131,0.0163,-0.0230,0.0039
2000-04,0.0223,-0.0241,-0.0101,-0.0541,0.0168,-0.0059,-0.0006,-0.0304,-0.0201,0.0188,0.0092,0.1028,-0.0269
2000-05,0.0149,0.0114,-0.0132,-0.0433,0.0062,-0.0034,0.0107,-0.0070,-0.0097,0.0146,0.0080,0.0704,-0.0122

In [23]:
erk.var_gaussian(er, level=1)

Convertible Arbitrage     0.034845
CTA Global                0.050336
Distressed Securities     0.031430
Emerging Markets          0.058070
Equity Market Neutral     0.014772
Event Driven              0.030853
Fixed Income Arbitrage    0.019519
Global Macro              0.024619
Long/Short Equity         0.039420
Merger Arbitrage          0.015355
Relative Value            0.021605
Short Selling             0.102130
Funds Of Funds            0.029385
dtype: float64

In [27]:
erk.var_gaussian(er["Distressed Securities"], level = 1, modified = True)

0.04966909110627921

In [31]:
erk.var_historic(er, level=1)

Convertible Arbitrage     0.031674
CTA Global                0.050938
Distressed Securities     0.042642
Emerging Markets          0.065496
Equity Market Neutral     0.019800
Event Driven              0.038540
Fixed Income Arbitrage    0.030748
Global Macro              0.022632
Long/Short Equity         0.045060
Merger Arbitrage          0.022654
Relative Value            0.021788
Short Selling             0.107684
Funds Of Funds            0.027200
dtype: float64

In [52]:
# Q4: Use the data to calculate the Books, Steel, Oils and Mines Indutries
ind = erk.get_ind_returns()
er = erk.annual_return(ind["2013":"2017"], 12)
l = ["Books", "Steel", "Oil", "Mines"]
cov = ind["2013":"2017"].cov()

/Users/phamthanh/Documents/ESSCA | MSc Finance & Data Analyst/9. Introduction to Portfolio Construction/kit.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ind = pd.read_csv("data/ind30_m_vw_rets.csv", header=0, index_col=0,parse_dates=True)/100

In [72]:
w_msr = erk.msr(riskfree_rate=0.01, er=er[l], cov=cov.loc[l,l])
w_msr

array([0.70933238, 0.29066762, 0.        , 0.        ])

In [ ]:
weights = pd.Series(w_msr, index=er[l].index)
weights

Books    0.709332
Steel    0.290668
Oil      0.000000
Mines    0.000000
dtype: float64

In [77]:
cov.loc[l,l]

          Books     Steel       Oil     Mines
Books  0.002720  0.001940  0.001637  0.001539
Steel  0.001940  0.004391  0.002122  0.003391
Oil    0.001637  0.002122  0.002697  0.002179
Mines  0.001539  0.003391  0.002179  0.005232

In [74]:
w_gmv = erk.gmv(cov.loc[l,l])
w_gmv

array([4.77024865e-01, 4.33680869e-19, 4.34112030e-01, 8.88631048e-02])

In [ ]:
weights_gmv = pd.Series(w_gmv, index=er[l].index)
weights_gmv.round(4

Books    4.770249e-01
Steel    4.336809e-19
Oil      4.341120e-01
Mines    8.886310e-02
dtype: float64